from __future__ import annotations

import numpy as np
from PIL import Image

from .. import grid as gr

THISTLE_ART = """
....P.P.P.P.P.P....
...PPPPPPPPPPPPP...
...PPPPPPPPPPPPP...
..PPPPPPPPPPPPPPP..
..PPPPPPPPPPPPPPP..
...PPPPPPPPPPPPP...
....PPPPPPPPPPP....
.....GGGGGGGGG.....
....GGGGGGGGGGG....
....GGGGGGGGGGG....
....GGGGGGGGGGG....
.....GGGGGGGGG.....
......GGGGGGG......
.......GGGGG.......
........GGG........
........GGG........
..GG....GGG....GG..
.GGGG...GGG...GGGG.
.GGGGG..GGG..GGGGG.
..GGGGG.GGG.GGGGG..
...GGGGGGGGGGGGG...
..GG.GGGGGGGGGG.GG.
.GGG..GGGGGGGG..GGG
..GGGG.GGGGGG.GGGG.
...GGGGGGGGGGGGGG..
.....GGGGGGGGGGG...
........GGG........
.....GG.GGG.GG.....
....GGGGGGGGGGG....
......GGGGGGG......
........GGG........
........GGG........
........GGG........
.......GGGGG.......
"""


THISTLE_SMALL_ART = """
.....P.P.P.P.P.....
....PPPPPPPPPPP....
...PPPPPPPPPPPPP...
...PPPPPPPPPPPPP...
....PPPPPPPPPPP....
......GGGGGGG......
.....GGGGGGGGG.....
.....GGGGGGGGG.....
......GGGGGGG......
.......GGGGG.......
........GGG........
........GGG........
..GG....GGG....GG..
.GGGG...GGG...GGGG.
..GGGGG.GGG.GGGGG..
...GGGGGGGGGGGGG...
.....GGG.GGG.GGG...
........GGG........
...GG...GGG...GG...
..GGGG..GGG..GGGG..
...GGGGGGGGGGGGG...
.....GGGGGGGGG.....
........GGG........
........GGG........
.......GGGGG.......
"""


def _art_to_array(art, bg, head, leaf):
    lines = art.strip("\n").split("\n")
    w = max(len(ln) for ln in lines)
    arr = np.full((len(lines), w), bg, dtype=np.uint8)
    for y, line in enumerate(lines):
        for x, ch in enumerate(line):
            if ch == "P":
                arr[y, x] = head
            elif ch == "G":
                arr[y, x] = leaf
    return arr


def thistle(bg, head, leaf):
    return _art_to_array(THISTLE_ART, bg, head, leaf)


def thistle_small(bg, head, leaf):
    """Compact thistle drawn for ~6 in tall at sc gauge (19 x 25 cells)."""
    return _art_to_array(THISTLE_SMALL_ART, bg, head, leaf)


def thistle_scaled(height_in, bg, head, leaf):
    """The hand-drawn thistle (designed at sc gauge: 19 x 34 cells = 5.4 x 8.5 in) resampled to
    `height_in` tall at the current gauge, aspect preserved."""
    base = thistle_small(bg, head, leaf) if height_in < 7.0 else thistle(bg, head, leaf)
    bh, bw = base.shape
    w_in = bw / 3.5 * (height_in / (bh / 4.0))
    tw, th = max(5, gr.cols(w_in)), max(8, gr.rows(height_in))
    img = Image.fromarray(base).resize((tw, th), Image.NEAREST)
    return np.array(img, dtype=np.uint8)


def bloom_icon(bg, head, calyx):
    """A tiny thistle 'carved in the centre of each link': head-colored crown over a calyx base."""
    cw, chh = max(3, gr.cols(1.0)), max(1, gr.rows(0.5))
    kw, kh = max(2, gr.cols(0.5)), max(1, gr.rows(0.5))
    w, h = cw, chh + kh
    arr = np.full((h, w), bg, dtype=np.uint8)
    arr[:chh, :] = head
    kx = (w - kw) // 2
    arr[chh:, kx:kx + kw] = calyx
    return arr
