import Compression
import Foundation

/// A read-only, name-addressed zip reader, enough to open a `.graphghan` bundle and no more.
///
/// Foundation has no zip reader, and the alternative to this file is a SwiftPM dependency. The
/// app's Xcode project is generated by XcodeGen and gitignored, so `Package.resolved` is not in
/// the repository: a dependency here would be pinned by tag in `project.yml` and by nothing else,
/// and it would be the one third-party thing in this repo that is not pinned by bytes *and* the
/// one that parses hostile input. The hardening below — traversal, bombs, caps, CRC — has to be
/// written on top of any library anyway; starting from "give me the bytes of the entry named X"
/// removes the unsafe API rather than documenting it. See the design spec §4.
///
/// What it refuses, rather than guesses at: zip64, encryption, data descriptors, multiple disks,
/// compression methods other than stored and deflate, names that could escape a directory, and
/// anything above the caps in `Limits`. A bundle needs none of them; if one ever does, that is a
/// fixture and a test.
public struct ZipArchive: Sendable {
    public enum ZipError: Error, Equatable {
        /// No end-of-central-directory record: not a zip at all.
        case notAZip
        /// A header or a run of bytes the archive claims exist runs off the end.
        case truncated(String)
        case multiDisk
        case zip64
        case encrypted(String)
        /// General-purpose bit 3: the sizes are after the data, not in the header.
        case dataDescriptor(String)
        case unsupportedMethod(String, UInt16)
        /// A name that could escape the directory it is unpacked into.
        case unsafeName(String)
        case malformedName(String)
        /// Two entries with one name: which a reader picks is a matter of taste, and a bundle
        /// whose `pattern.json` means different things to different readers is not one to open.
        case duplicateName(String)
        case tooManyEntries(Int)
        case entryTooLarge(String, UInt64)
        case archiveTooLarge(UInt64)
        /// The bytes do not match what the central directory says they are.
        case corrupt(String)
        case notFound(String)
    }

    /// Caps, checked against the declared sizes when the archive is opened and again against the
    /// bytes actually produced, so neither a lying header nor a decompression bomb gets through.
    public enum Limits {
        public static let entries = 1024
        public static let entrySize: UInt64 = 32 << 20
        public static let totalSize: UInt64 = 64 << 20
    }

    struct Entry: Sendable {
        let name: String
        let method: UInt16
        let crc: UInt32
        let compressedSize: UInt64
        let uncompressedSize: UInt64
        let localHeaderOffset: UInt64
    }

    private let data: Data
    private let entries: [String: Entry]
    /// Central-directory order, which is the order the writer wrote them in.
    public let names: [String]

    public init(_ data: Data) throws {
        self.data = data
        let eocd = try Self.endOfCentralDirectory(in: data)
        var offset = eocd.directoryOffset
        var ordered: [Entry] = []
        var byName: [String: Entry] = [:]
        var total: UInt64 = 0
        for _ in 0..<eocd.entryCount {
            let (entry, next) = try Self.centralDirectoryEntry(in: data, at: offset)
            total += entry.uncompressedSize
            guard total <= Limits.totalSize else { throw ZipError.archiveTooLarge(total) }
            guard byName[entry.name] == nil else { throw ZipError.duplicateName(entry.name) }
            ordered.append(entry)
            byName[entry.name] = entry
            offset = next
        }
        self.entries = byName
        self.names = ordered.map(\.name)
    }

    public func contains(_ name: String) -> Bool { entries[name] != nil }

    /// The entry's bytes, inflated if it is deflated, checked against the central directory's
    /// length and CRC-32 before it is returned.
    public func data(named name: String) throws -> Data {
        guard let entry = entries[name] else { throw ZipError.notFound(name) }
        let start = try Self.dataStart(in: data, for: entry)
        let end = start + Int(entry.compressedSize)
        guard end <= data.count else { throw ZipError.truncated(name) }
        let raw = data.subdata(in: (data.startIndex + start)..<(data.startIndex + end))
        let out: Data
        switch entry.method {
        case 0:
            out = raw
        case 8:
            out = try Self.inflate(raw, expecting: Int(entry.uncompressedSize), name: name)
        default:
            throw ZipError.unsupportedMethod(name, entry.method)
        }
        // The declared length is checked here as well as at open time: `compression_decode_buffer`
        // stops at the destination size, so a stream that would produce more bytes than declared
        // comes back looking exactly right. The CRC is what catches that one.
        guard out.count == Int(entry.uncompressedSize) else { throw ZipError.corrupt(name) }
        guard CRC32.compute(out) == entry.crc else { throw ZipError.corrupt(name) }
        return out
    }

    // MARK: - parsing

    private struct EOCD {
        let entryCount: Int
        let directoryOffset: Int
    }

    private static let eocdSignature: UInt32 = 0x0605_4b50
    private static let eocd64LocatorSignature: UInt32 = 0x0706_4b50
    private static let centralSignature: UInt32 = 0x0201_4b50
    private static let localSignature: UInt32 = 0x0403_4b50
    /// 22 bytes of record plus the largest comment a zip can carry.
    private static let maxEOCDSearch = 22 + 0xFFFF

    private static func endOfCentralDirectory(in data: Data) throws -> EOCD {
        guard data.count >= 22 else { throw ZipError.notAZip }
        let lowest = max(0, data.count - maxEOCDSearch)
        var found: Int?
        var i = data.count - 22
        while i >= lowest {
            if u32(data, i) == eocdSignature { found = i; break }
            i -= 1
        }
        guard let eocd = found else { throw ZipError.notAZip }
        guard u16(data, eocd + 4) == 0, u16(data, eocd + 6) == 0 else { throw ZipError.multiDisk }
        let onThisDisk = u16(data, eocd + 8)
        let count = u16(data, eocd + 10)
        let size = u32(data, eocd + 12)
        let offset = u32(data, eocd + 16)
        guard onThisDisk == count else { throw ZipError.multiDisk }
        // zip64 announces itself two ways: sentinel values here, and a locator record just before
        // this one. Either is refused; neither is anything a bundle needs.
        guard count != 0xFFFF, size != 0xFFFF_FFFF, offset != 0xFFFF_FFFF else { throw ZipError.zip64 }
        if eocd >= 20, u32(data, eocd - 20) == eocd64LocatorSignature { throw ZipError.zip64 }
        guard Int(count) <= Limits.entries else { throw ZipError.tooManyEntries(Int(count)) }
        let directoryEnd = Int(offset) + Int(size)
        guard directoryEnd <= data.count, Int(offset) <= eocd else { throw ZipError.truncated("central directory") }
        return EOCD(entryCount: Int(count), directoryOffset: Int(offset))
    }

    private static func centralDirectoryEntry(in data: Data, at offset: Int) throws -> (Entry, Int) {
        guard offset + 46 <= data.count else { throw ZipError.truncated("central directory") }
        guard u32(data, offset) == centralSignature else { throw ZipError.truncated("central directory") }
        let flags = u16(data, offset + 8)
        let method = u16(data, offset + 10)
        let crc = u32(data, offset + 16)
        let compressed = UInt64(u32(data, offset + 20))
        let uncompressed = UInt64(u32(data, offset + 24))
        let nameLength = Int(u16(data, offset + 28))
        let extraLength = Int(u16(data, offset + 30))
        let commentLength = Int(u16(data, offset + 32))
        let diskStart = u16(data, offset + 34)
        let localOffset = u32(data, offset + 42)
        let next = offset + 46 + nameLength + extraLength + commentLength
        guard next <= data.count else { throw ZipError.truncated("central directory") }

        let nameBytes = data.subdata(in: (data.startIndex + offset + 46)..<(data.startIndex + offset + 46 + nameLength))
        guard let name = String(data: nameBytes, encoding: .utf8) else {
            throw ZipError.malformedName("<not utf-8>")
        }
        try checkName(name)
        guard diskStart == 0 else { throw ZipError.multiDisk }
        guard compressed != 0xFFFF_FFFF, uncompressed != 0xFFFF_FFFF, localOffset != 0xFFFF_FFFF else {
            throw ZipError.zip64
        }
        guard flags & 0x0001 == 0 else { throw ZipError.encrypted(name) }
        guard flags & 0x0008 == 0 else { throw ZipError.dataDescriptor(name) }
        guard method == 0 || method == 8 else { throw ZipError.unsupportedMethod(name, method) }
        guard uncompressed <= Limits.entrySize else { throw ZipError.entryTooLarge(name, uncompressed) }
        guard compressed <= Limits.entrySize else { throw ZipError.entryTooLarge(name, compressed) }
        guard Int(localOffset) < data.count else { throw ZipError.truncated(name) }
        if name.hasSuffix("/"), uncompressed != 0 { throw ZipError.malformedName(name) }

        let entry = Entry(name: name, method: method, crc: crc, compressedSize: compressed,
                          uncompressedSize: uncompressed, localHeaderOffset: UInt64(localOffset))
        return (entry, next)
    }

    /// A name that could name a file outside the directory it is written into, or no file at all.
    private static func checkName(_ name: String) throws {
        guard !name.isEmpty else { throw ZipError.malformedName(name) }
        guard !name.hasPrefix("/") else { throw ZipError.unsafeName(name) }
        guard !name.contains("\\") else { throw ZipError.unsafeName(name) }
        guard !name.contains("\0") else { throw ZipError.malformedName(name) }
        guard !name.split(separator: "/", omittingEmptySubsequences: false).contains("..") else {
            throw ZipError.unsafeName(name)
        }
    }

    /// Where an entry's bytes begin. Only the local header's own name and extra lengths are
    /// trusted — every other field comes from the central directory, which is the copy a zip
    /// writer updates last and a reader is meant to believe.
    private static func dataStart(in data: Data, for entry: Entry) throws -> Int {
        let offset = Int(entry.localHeaderOffset)
        guard offset + 30 <= data.count else { throw ZipError.truncated(entry.name) }
        guard u32(data, offset) == localSignature else { throw ZipError.corrupt(entry.name) }
        let nameLength = Int(u16(data, offset + 26))
        let extraLength = Int(u16(data, offset + 28))
        let start = offset + 30 + nameLength + extraLength
        guard start <= data.count else { throw ZipError.truncated(entry.name) }
        return start
    }

    private static func inflate(_ raw: Data, expecting size: Int, name: String) throws -> Data {
        guard size > 0 else { return Data() }
        guard !raw.isEmpty else { throw ZipError.corrupt(name) }
        var out = Data(count: size)
        let written = out.withUnsafeMutableBytes { destination -> Int in
            guard let dst = destination.bindMemory(to: UInt8.self).baseAddress else { return 0 }
            return raw.withUnsafeBytes { source -> Int in
                guard let src = source.bindMemory(to: UInt8.self).baseAddress else { return 0 }
                // COMPRESSION_ZLIB is raw DEFLATE on Apple's platforms, which is what a zip entry
                // holds -- no zlib header, no adler checksum.
                return compression_decode_buffer(dst, size, src, raw.count, nil, COMPRESSION_ZLIB)
            }
        }
        guard written == size else { throw ZipError.corrupt(name) }
        return out
    }

    // MARK: - little-endian reads

    private static func u16(_ data: Data, _ offset: Int) -> UInt16 {
        let i = data.startIndex + offset
        guard i + 2 <= data.endIndex else { return 0 }
        return UInt16(data[i]) | UInt16(data[i + 1]) << 8
    }

    private static func u32(_ data: Data, _ offset: Int) -> UInt32 {
        let i = data.startIndex + offset
        guard i + 4 <= data.endIndex else { return 0 }
        return UInt32(data[i]) | UInt32(data[i + 1]) << 8 | UInt32(data[i + 2]) << 16 | UInt32(data[i + 3]) << 24
    }
}

/// CRC-32 (IEEE), which a zip entry carries and `Compression` does not provide.
enum CRC32 {
    private static let table: [UInt32] = (0..<256).map { i -> UInt32 in
        var c = UInt32(i)
        for _ in 0..<8 { c = (c & 1 == 1) ? (0xEDB8_8320 ^ (c >> 1)) : (c >> 1) }
        return c
    }

    static func compute(_ data: Data) -> UInt32 {
        var crc: UInt32 = 0xFFFF_FFFF
        for byte in data { crc = table[Int((crc ^ UInt32(byte)) & 0xFF)] ^ (crc >> 8) }
        return crc ^ 0xFFFF_FFFF
    }
}
